author: alexkomrakov@gmail.com
description: >
        Json api server with random data placeholders
filesets:
    includes:
    excludes:
        - \.git
    depth: 3
settings:
        targetdir: ""
        build: |
            test -d Godeps && go(){ godep go "$@";} ; go install -v
        outfiles:
            - packer